resources:
- ../../base


# example patch: change replica count
patches:
- patch: |
	apiVersion: apps/v1
	kind: Deployment
	metadata:
	  name: backend
	spec:
	  replicas: 2
  target:
	kind: Deployment
	name: backend